# Site settings
title: "BioVis 2020"
email: "website@biovis.net"
description: "Biological Data Visualization"
baseurl: "/2020"
#url: "http://biovis.github.io/biovis_2016"
url: "http://biovis.net"
conferenceshort: "BioVis 2020"
#FIX ME: the event number is most likely not correct
eventNum: "10th" 
IEEEconferencedate: "October, 2020"
IEEEconferenceplace: "Salt Lake City, USA"
ISMBconferencedate: "July 15, 2020"
ISMBconferenceplace: "Montreal, Canada"
year: 2020
ismblink: "https://www.iscb.org/ismb2020"

# Old deadlines so I remember what they're called
# When everything breaks
#IEEE_deadline_submission: "TBD"
#IEEE_deadline_notification: "TBD"
#IEEE_deadline_camera: "TBD"
#IEEE_deadline_poster: "TBD"

#ISMB_hl_and_nresearch_submission: "TBD"
#ISMB_deadline_poster: "TBD"
#ISMB_hl_and_nresearch_notiication: "TBD"

ismb_paper_submission_deadline: "30 January, 2020"
ismb_paper_conditional_accept: "March, 2020"
ismb_paper_revised: "March, 2020"
ismb_paper_final_acceptance: "April, 2020"

biovis_paper_submission_deadline: "TBD"

ismb_abstract_submission_deadline: "April 16, 2020"

ismb_poster_submission_deadline: "May 28, 2020"
ismb_poster_accept: "June 4, 2020"
ismb_poster_oral_notification: TBD"

ismb_highlights_submission_deadline: "TBD"
ismb_highlights_accept: "TBD"

bmc_submission_deadline: ""
bmc_conditional_accept: ""
bmc_final_accpet: ""

# Build settings
markdown: kramdown

collections:
- posters_ISMB

google_analytics: "'UA-22015250-1'"
use_analytics: true
encoding: utf-8
